### ISSUE TITLE
Add boolean parameter in settings to show alerts.

### ISSUE THREAD

**Issue by shenrgc** [yigitozkavci/wowwizard#16]
Add a boolean parameter in wizard settings to show the warning of change an step which other are dependents.
It's needed to check this parameter in `_nextStep()` function and depending on it, call `_clearFutureSteps($step);` or not.

**Comment by saksham-s** [comment]
hello.Is this issue open.It is my first time on open source and i would like to contribute.

**Comment by yigitozkavci** [comment]
@saksham15082 I'm afraid it has been already done by @shenrgc, you can check out other issues though :)

**Comment by saksham-s** [comment]
No problem thanks.
