### ISSUE TITLE
Design - adding more templates

### ISSUE THREAD

**Issue by yigitozkavci** [yigitozkavci/wowwizard#2]
We currently have `pomegranate` and `blueberry` template, that would be nice to have more templates with sophisticated color schemes.

**Comment by ynrstp** [comment]
Hi @yigitozkavci, I can help with this!

**Comment by yigitozkavci** [comment]
Hi there @ynrstp, that would be awesome, thanks :)

**Comment by RyanFitzgerald** [comment]
Hey @yigitozkavci , I'd love to help out with this as well! Can I ask what you mean by more sophisticated color schemes?

**Comment by yigitozkavci** [comment]
Hi @RyanFitzgerald, this is rather a design issue, and by more sophisticated, I meant theme to be well-thought in terms of harmony in its colors.

Every website has its own style and colors, and I want this wizard to have more choices of pre-defined themes in it.

Of course you can work on this too, thanks :)

**Comment by yigitozkavci** [comment]
Since we have enough templates for now, closing it.
