### ISSUE TITLE
Creating demo in wiki page & adding link to README.md

### ISSUE THREAD

**Issue by yigitozkavci** [yigitozkavci/wowwizard#3]
We already have examples in `/examples` directory, and we need to add them to wiki page;
You should edit `gh-pages` branch of this repository in order to edit wiki page, good luck! :)

**Comment by RCMainak** [comment]
Hello! how you doing?

By wiki page do you mean http://yigitozkavci.github.io/wowwizard/? If so where do you want me to add it!

I would like to get a t-shirt if you know what i mean :tongue:

**Comment by yigitozkavci** [comment]
A seperate demo page would be nice, like adding it to http://yigitozkavci.github.io/wowwizard/demo.html by creating that page in `gh-pages` branch and using this very plugin, thanks for your interest by the way :)

**Comment by RCMainak** [comment]
As I can see you already have a demo page set up [here](http://yigitozkavci.github.io/wowwizard/examples/example1/). We can link that page in the homepage of this project, I think that would be more appropriate instead of making a new page.

**Comment by yigitozkavci** [comment]
Yes, you are right! I didn't think of accessing examples from `gh-pages`. You can add the demo link both to the README and wiki page, I think people would want to see demo link in both, thanks! :)

**Comment by RCMainak** [comment]
@yigitozkavci can you please clarify which page you're referring to when you're saying "wiki page"

**Comment by yigitozkavci** [comment]
**Wiki page:** http://yigitozkavci.github.io/wowwizard
**README:** https://github.com/yigitozkavci/wowwizard/blob/master/README.md
